function createClubs() {
  const clubList = document.getElementById("clubList");

  const clubs = [
  {
    "staff": "Antoni, Austin & Gardner, Elijah",
    "club": "Rugby (Girls)",
    "email": "austinantoni@gmail.com & egardner@hse.k12.in.us",
    "description": "hi this is a description",
    "Time": "After",
    "Type": "Sports",
    "Day": "Monday"

  },
  {
    "staff": "Armey, Julie",
    "club": "Orchestra Club",
    "email": "jarmey@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Bandura, Jacob",
    "club": "",
    "email": "jbandura@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Barfield, Alexis", 
    "club": "Alaska Native and Native American Club",
    "email": "abarfield@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Black, Scott",
    "club": "Asian Student Union",
    "email": "sdblack@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Bockenfeld, Matt",
    "club": "Muslim Student Association (MSA)",
    "email": "mbockenfeld@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Brown, Lisa",
    "club": "Art Club",
    "email": "lgbrown@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Buckman, Bill",
    "club": "Poker Club",
    "email": "mbuckman@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Carson, Beth",
    "club": "Care Crafts Project",
    "email": "acarson@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Chan, Brooke",
    "club": "Disney Lorcana TCG Club",
    "email": "bchan@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Chan, Brooke",
    "club": "Magic: The Gathering",
    "email": "bchan@hse.k12.in.us",
    "description" : "Students play the Magic: The Gathering trading card game, discuss strategies and cards, and socialize.",
    "Time" : "After",
    "Type" : "Games",
    "Day" : "Wednesday",
  },
  {
    "staff": "Chop, Dahnya",
    "club": "French Club",
    "email": "dchop@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Curtis, Liz",
    "club": "GSA",
    "email": "lcurtis@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Curtis, Steven",
    "club": "Dungeons & Dragons Club",
    "email": "scurtis@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Czech, Mike",
    "club": "School of Rock",
    "email": "mczech@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Delucenay, Katie",
    "club": "Baking Club",
    "email": "kdelucenay@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Delucenay, Katie",
    "club": "Off the Clock (OTC)",
    "email": "kdelucenay@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Druelinger, Sarah",
    "club": "Ping Pong Club",
    "email": "sdruelinger@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Farrand, Angela",
    "club": "American Sign Language (ASL) Club",
    "email": "afarrand@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Manoharan, Vennila",
    "club": "Crochet Club",
    "email": "vmanoharan@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Ferguson, Heather",
    "club": "Senior Smile Society",
    "email": "hferguson@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "French, Brigham",
    "club": "Chess Club",
    "email": "bfrench@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "French, Brigham",
    "club": "AI Club",
    "email": "bfrench@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Gastineau, Chelley",
    "club": "Bring Change to Mind",
    "email": "cgastineau@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Greisinger, Jessica",
    "club": "Swiss-Mix Club (formerly German Club)",
    "email": "jgeisinger@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Geisinger, Robin",
    "club": "Swiss-Mix Club (formerly German Club)",
    "email": "rgeisinger@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Goodwin, Danielle",
    "club": "Unified Dance",
    "email": "dgoodwin@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Gutting, Stephanie",
    "club": "Harry Potter Club",
    "email": "sgutting@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Gutting, Stephanie",
    "club": "Spanish Club",
    "email": "sgutting@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Gutting, Stephanie",
    "club": "Unified Dance",
    "email": "sgutting@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Hamilton, Terri",
    "club": "Student Organ Donor Advocates (SODA)",
    "email": "thamilton@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Harris, Ryan",
    "club": "Badminton Cub",
    "email": "rharris@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Harris, Ryan",
    "club": "Computer Science Club",
    "email": "rharris@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Harris, Ryan",
    "club": "Cricket Club",
    "email": "rharris@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Harris, Ryan",
    "club": "Desi Student Association",
    "email": "rharris@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Harris, Ryan",
    "club": "Sports Trading Card Club",
    "email": "rharris@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Helmkamp, Michelle",
    "club": "Spanish Club",
    "email": "mhelmkamp@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Huppenthal, Suzie",
    "club": "Do Something Club",
    "email": "shuppenthal@hse.k12.in.us",
    "description" : "It is based on DoSomething.org which empowers young people who want to build a better world. Instead of complaining, you do \"something\" to fix the problem. We have cleaned the school, done clothing drives, helped at the humane society and nursing homes. Be the change!",
    "Time" : "After",
    "Type" : "Service",
    "Day" : "Tuesday",
  },
  {
    "staff": "Isom, Renee",
    "club": "3D Printing Club",
    "email": "risom@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Isom, Renee",
    "club": "Cultural Connections Club",
    "email": "risom@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Isom, Renee",
    "club": "FHS Reads Book Club",
    "email": "risom@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Isom, Renee",
    "club": "Future Black Leaders",
    "email": "risom@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Isom, Renee",
    "club": "Roll the Tape",
    "email": "risom@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Jacobs, Kelli",
    "club": "Anime Club",
    "email": "kjacobs@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Jordan, Monica",
    "club": "Rock Climbing Club",
    "email": "mrjordan@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Kapitan, Jacob",
    "club": "Bible Study Group",
    "email": "jkapitan@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Kapitan, Jacob",
    "club": "Dungeons & Dragons Club",
    "email": "jkapitan@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Kapitan, Jacob",
    "club": "E-Sports Club",
    "email": "jkapitan@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Kapitan, Jacob",
    "club": "Pokemon Club",
    "email": "jkapitan@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Keithley, Maxwell",
    "club": "Environmental Club",
    "email": "mkeithley@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Kixmiller, Lori",
    "club": "Student Government (Sponsor)",
    "email": "lkixmiller@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Knapp, Erin",
    "club": "2000s Fun!",
    "email": "eknapp@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Knapp, Erin",
    "club": "Create for Kids",
    "email": "eknapp@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Knapp, Erin",
    "club": "Yoga Club",
    "email": "eknapp@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Kohler, Chad",
    "club": "Marching Band",
    "email": "ckohler@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Horn, Sara",
    "club": "Women in S.T.E.M.",
    "email": "shorn@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Kuhn, Lance",
    "club": "Chemistry Club",
    "email": "lkuhn@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Laffin, Bill",
    "club": "Ski Club",
    "email": "blaffin@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Lawrence, Samuel",
    "club": "Future Farmers of America (FFA)",
    "email": "slawrence@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Lidy, Shelley",
    "club": "Better Help Club",
    "email": "slidy@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Luna, Madeleine",
    "club": "Badminton Club",
    "email": "mluna@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Lyons, Suzanne",
    "club": "Orchestra Club",
    "email": "slyons@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Macmillan, Jordan",
    "club": "FHS \"Pubs\" Club (Publications)",
    "email": "jmacmillan@hse.k12.in,us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Masterson, Ray",
    "club": "Music & Sound Recording Club",
    "email": "rmasterson@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "McCabe, Shanna",
    "club": "CATS (Creating Action Through Service)",
    "email": "smccabe@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "McCabe, Shanna",
    "club": "FHS Reads Book Club",
    "email": "smccabe@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Meador, Taylor",
    "club": "Aura8 Dance Club",
    "email": "tmeador@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Meador, Taylor",
    "club": "K-Pop Club",
    "email": "tmeador@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Meador, Taylor",
    "club": "ENL Club",
    "email": "tmeador@hse.k12.in.us",
    "description" : "ENL Ambassadors is a service-based leadership program designed to engage ENL and immigrant students as leaders at FHS. The main goals of the club are to assist newly enrolled students who do not speak English fluently, tutor English learners, and promote cultural awareness in our community. Members must be bilingual and have been enrolled in an ENL program at some point.",
    "Time" : "After",
    "Type" : "Service",
    "Day" : "Varies",
  },
  {
    "staff": "Miller, Audra",
    "club": "I'm Just a Girl",
    "email": "almiller@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Noyes, Summer",
    "club": "Senior Smile Society",
    "email": "snoyes@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Ondish, Kelsey",
    "club": "Improv Club",
    "email": "kondish@hse.k12.in.us",
    "description": "",
    "Time": "After",
    "Type": "Arts",
    "Day": "Tueday"

  },
  {
    "staff": "Ondish, Kelsey",
    "club": "LLS Club (Leukemia & Lymphoma Society)",
    "email": "kondish@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Paternoster, Liz",
    "club": "We The People (Head Coach)",
    "email": "lpaternoster@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Placzek, Sharon",
    "club": "Hispanic Heritage Club",
    "email": "splaczek@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Rund, Emma",
    "club": "Drama Club / Theatre Fishers",
    "email": "erund@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Schooley, Patrick",
    "club": "Champions Together",
    "email": "pschooley@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Schuh, Tori",
    "club": "Best Buddies",
    "email": "vschuh@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Schulhof, Beth",
    "club": "Pickleball Club",
    "email": "eschulhof@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Seland, Glenn",
    "club": "Animation Club",
    "email": "gseland@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Seland, Glenn",
    "club": "Film Club",
    "email": "gseland@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Shafer, Gretchen",
    "club": "Gratitude Bowls",
    "email": "gshafer@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Shuck, Jamison",
    "club": "African Association Culture Club",
    "email": "jshuck@hse.k12.in.us",
    "description" : "This club is a space for any Africans, students of African descent, or anyone who simply wants to learn more about African culture. It’s open to all. The goal is to bring people together for community and education. We play games, learn from each other, share cultural foods, watch African movies, find ways to help local African businesses, etc.",
    "Time" : "After",
    "Type" : "Service",
    "Day" : "Tuesday",
  },
  {
    "staff": "Smith, Andy",
    "club": "Tech Crew / Theatre Fishers",
    "email": "asmith@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Snyder, Tammy",
    "club": "STEMsters",
    "email": "tsnyder@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Snyder, Tammy",
    "club": "CRU (Student Venture)",
    "email": "tsnyder@hse.k12.in.us",
    "description" : "Who We Are: Cru is a caring community of people who want to help each other take the next step in their journey toward Jesus. Whether you’re exploring faith or looking to grow deeper, you’re welcome here.What We Do at Our Weekly MeetingsEach week, we gather in small groups to connect, grow, and encourage one another. We spend time building meaningful relationships, talking about life, reading the Bible, and having honest conversations about faith. It’s a space to be real, ask questions, and experience how Jesus makes a difference in everyday life.Wherever you are on your journey, we’d love to walk with you.",
    "Time" : "After",
    "Type" : "Service",
    "Day" : "Monday",
  },
  {
    "staff": "Spencer, Tammie",
    "club": "Animal Alliance",
    "email": "tspencer@hse.k12.in.us",
    "description" : "Animal Alliance is a club that exposes its members to a variety of animal-based volunteer opportunities in the greater Indianapolis area. We typically volunteer twice a month (with a varying schedule). We have hosted volunteer opportunities at the Hamilton County Humane Society, Oinking Acres, Koteewi Stables, and others!Join the Remind (@animala) for information on club meetings/volunteer opportunities!",
    "Time" : "After",
    "Type" : "Service",
    "Day" : "Varies",
  },
  {
    "staff": "Steange, Susanne",
    "club": "Gymnastics",
    "email": "strangesusie@gmail.com",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Swaim, Matt",
    "club": "Tiger Ambassadors",
    "email": "mswaim@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Thomas, William",
    "club": "East African Student Association",
    "email": "wthomas@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Thompson-Mejias, Terri",
    "club": "Euchre Club",
    "email": "tthompsonmejias@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Thompson-Mejias, Terri",
    "club": "Latino Student Union",
    "email": "tthompsonmejias@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Tribolet, Braden",
    "club": "Tiger Spirit Leaders",
    "email": "btribolet@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Turner, Dave",
    "club": "Economics Club",
    "email": "dturner@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Turner, Dave",
    "club": "Investment Club",
    "email": "dturner@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Tysen, Jessica",
    "club": "Bowling Club",
    "email": "jessicanstevens@gmail.com",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Vanlandingham, Renee",
    "club": "Fishers Tutors",
    "email": "rvanlandingham@hse.k12.in.us",
    "description": "FHS Tutors is a club that connects tutors with kids across HSE Schools. We tutor at Riverside JH every Wednesday from 4-5pm, and at Fishers JH from 4-5pm. Additionally, you can sign up to be an in-school tutor and be paired with a high school student who requests a tutor. Please join the Remind with code @tutorsfhs",
    "Time": "After",
    "Type": "Service",
    "Day": "Varies"
  },
  {
    "staff": "VanTrees, Leah",
    "club": "W.R.I.T.E. Club",
    "email": "lvantrees@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Vaughn, Alisa",
    "club": "ENL Math Tutoring",
    "email": "avaughn@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Votaw, Lauren",
    "club": "Fellowship of Christian Athletes (FCA)",
    "email": "lvotaw@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Walker, Sarah",
    "club": "MED LIFE",
    "email": "swalker@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Werbe, Jim",
    "club": "Intramural Basketball",
    "email": "jwerbe@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "White, Jessica",
    "club": "Key Club",
    "email": "jlwhite@hse.k12.in.us",
    "description" : "",
    "Time" : "",
    "Type" : "",
    "Day" : "",
  },
  {
    "staff": "Young, Kate",
    "club": "Million Meal Movement",
    "email": "kyoung@hse.k12.in.us",
    "description" : "Million Meal Movement works to raise money and supplies to help food insecure people in Hamilton County and beyond. We raise money throughout the year to hold a meal packing event on the Day of Service, where we pack 15-20,000 meals in one day!",
    "Time" : "After",
    "Type" : "Service",
    "Day" : "Tuesday",
  }
]

  // Sort clubs alphabetically 
  clubs.sort((a, b) => {
    const nameA = a.club.toLowerCase();
    const nameB = b.club.toLowerCase();

    const Astart = /^\d/.test(nameA);
    const Bstart = /^\d/.test(nameB);

    if (Astart && !Bstart) return -1;
    if (!Astart && Bstart) return 1;

    return nameA.localeCompare(nameB);
  });
  // Create club boxes
  function createClubs() {
    const clubList = document.getElementById("clubList");
    clubList.innerHTML = "";

    clubs.forEach(club => {
      const liElement = document.createElement("li");
      liElement.classList.add("club-box");

      liElement.innerHTML = `
      <img 
        src="star.png" 
        alt="favorite star" 
        class="favorite-star" 
        style="width:25px; height:25px; cursor:pointer;"
      >
      <h3 class="clubBoxesFontSize">${club.club}</h3>
      <p class="clubBoxesFontSize">${club.staff}</p>
      <p class="clubBoxesEmailSize">${club.email}</p>

      
      <div class="club-description">
        ${club.description || "No description available."}
      </div>
    `;

      const star = liElement.querySelector(".favorite-star");
      // favoriteing functionality
      const favorites = JSON.parse(localStorage.getItem("favorites")) || [];
      if (favorites.some(fav => fav.club === club.club)) {
        star.src = "goldStar.jpeg";
        star.classList.add("favorited");
      }

      star.addEventListener("click", (e) => {
        e.stopPropagation();
        const target = e.target;
        let favorites = JSON.parse(localStorage.getItem("favorites")) || [];

        target.classList.toggle("favorited");

        if (target.classList.contains("favorited")) {
          target.src = "goldStar.jpeg";
          if (!favorites.some(fav => fav.club === club.club)) {
            favorites.push(club);
          }
        } else {
          target.src = "star.png";
          favorites = favorites.filter(fav => fav.club !== club.club);
        }

        localStorage.setItem("favorites", JSON.stringify(favorites));
      });

      clubList.appendChild(liElement);
    });
  }

  createClubs();
}





